services:
  prcybr-backend-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: prcybr/pr-cybr-backend-agent:latest
    container_name: prcybr-backend-agent
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - pr-cybr-net
    ports:
      - "8080:80"  # Adjust this port as necessary for your Agent

networks:
  pr-cybr-net:
    driver: bridge
