#############################################
# Terraform Cloud Workspace Variables Mapping
# Populate these values in TFC to keep GitHub
# workflows and Terraform plans in sync.
#############################################

GITHUB_TOKEN                      = "REPLACE_WITH_GITHUB_TOKEN"
TFC_TOKEN                         = "REPLACE_WITH_TFC_TOKEN"
DOCKERHUB_TOKEN                   = "REPLACE_WITH_DOCKERHUB_TOKEN"
DOCKERHUB_USERNAME                = "REPLACE_WITH_DOCKERHUB_USERNAME"
PR_CYBR_DOCKER_PASS               = "REPLACE_WITH_DOCKER_PASSWORD"
PR_CYBR_DOCKER_USER               = "REPLACE_WITH_DOCKER_USERNAME"
GLOBAL_DOMAIN                     = "REPLACE_WITH_GLOBAL_DOMAIN"
GLOBAL_ELASTIC_URI                = "REPLACE_WITH_ELASTIC_URI"
GLOBAL_GRAFANA_URI                = "REPLACE_WITH_GRAFANA_URI"
GLOBAL_KIBANA_URI                 = "REPLACE_WITH_KIBANA_URI"
GLOBAL_PROMETHEUS_URI             = "REPLACE_WITH_PROMETHEUS_URI"
GLOBAL_TAILSCALE_AUTHKEY          = "REPLACE_WITH_TAILSCALE_AUTHKEY"
GLOBAL_TRAEFIK_ACME_EMAIL         = "REPLACE_WITH_TRAEFIK_ACME_EMAIL"
GLOBAL_TRAEFIK_ENTRYPOINTS        = "REPLACE_WITH_TRAEFIK_ENTRYPOINTS"
GLOBAL_ZEROTIER_NETWORK_ID        = "REPLACE_WITH_ZEROTIER_NETWORK_ID"
AGENT_ACTIONS                     = "REPLACE_WITH_AGENT_ACTIONS_TOKEN"
AGENT_COLLAB                      = "REPLACE_WITH_AGENT_COLLAB_TOKEN"
NOTION_DISCUSSIONS_ARC_DB_ID      = "REPLACE_WITH_NOTION_DISCUSSIONS_ARC_DB_ID"
NOTION_ISSUES_BACKLOG_DB_ID       = "REPLACE_WITH_NOTION_ISSUES_BACKLOG_DB_ID"
NOTION_KNOWLEDGE_FILE_DB_ID       = "REPLACE_WITH_NOTION_KNOWLEDGE_FILE_DB_ID"
NOTION_PAGE_ID                    = "REPLACE_WITH_NOTION_PAGE_ID"
NOTION_PR_BACKLOG_DB_ID           = "REPLACE_WITH_NOTION_PR_BACKLOG_DB_ID"
NOTION_PROJECT_BOARD_BACKLOG_DB_ID = "REPLACE_WITH_NOTION_PROJECT_BOARD_BACKLOG_DB_ID"
NOTION_TASK_BACKLOG_DB_ID         = "REPLACE_WITH_NOTION_TASK_BACKLOG_DB_ID"
NOTION_TOKEN                      = "REPLACE_WITH_NOTION_TOKEN"
