name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: |
          python -m unittest discover tests

  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t prcybr/pr-cybr-backend-agent:latest .

      - name: Test Docker image
        run: |
          docker run --rm prcybr/pr-cybr-backend-agent:latest python -m unittest discover tests

  docker-compose-test:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test docker-compose configuration
        run: |
          docker compose config

      - name: Build with docker-compose
        run: |
          docker compose build

      - name: Run docker-compose (verify it starts)
        run: |
          docker compose up -d
          sleep 5
          docker compose ps
          docker compose down
