name: codex-commit-discussions

on:
  commit_comment:
    types:
      - created

jobs:
  discussion-triage:
    name: Log commit discussions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Summarize discussion metadata
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment;
            if (!comment) {
              core.info('No comment payload found.');
              return;
            }
            core.info(`Commit comment by ${comment.user.login}: ${comment.body.substring(0, 120)}`);
      - name: Archive conversation context
        run: |
          mkdir -p .github/discussion-cache
          echo "${{ github.event.comment.body }}" > .github/discussion-cache/latest.txt
          echo "Discussion context archived for downstream agents."
