name: Deploy with Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_PASSWORD != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Prepare deployment environment file
        env:
          DEPLOY_ENV_FILE: ${{ secrets.DEPLOY_ENV_FILE }}
        run: |
          if [ -n "$DEPLOY_ENV_FILE" ]; then
            printf "%s" "$DEPLOY_ENV_FILE" > .env
          elif [ ! -f .env ]; then
            echo "No DEPLOY_ENV_FILE secret provided and .env file not found in repository."
            exit 1
          fi

      - name: Run Docker Compose deployment
        run: docker compose up -d --build

      - name: Show running services
        run: docker compose ps
