name: notion-sync-tests

on:
  pull_request:
    branches:
      - codex
      - agents
      - dev
      - main
    paths:
      - 'src/shared/notion_sync.py'
      - 'tests/test_notion_sync.py'
      - 'requirements.txt'
      - '.github/workflows/notion-sync-tests.yml'
  push:
    branches:
      - codex
      - agents
      - dev
    paths:
      - 'src/shared/notion_sync.py'
      - 'tests/test_notion_sync.py'
      - 'requirements.txt'

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run Notion sync tests
        env:
          GITHUB_TOKEN: ${{ secrets.READ_ONLY_GITHUB_TOKEN || github.token }}
        run: |
          pytest tests/test_notion_sync.py -vv

