name: notion-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"  # optional hourly sync
  push:
    branches:
      - codex
      - agents
  pull_request:
    branches:
      - main

permissions:
  contents: read   # Principle of least privilege for GitHub token access

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AGENT_ACTIONS }} # Scoped PAT limited to repo/workflow access

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Notion sync
        env:
          # The Notion integration token should only have read/insert/update scopes.
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_PARENT_PAGE_ID: ${{ secrets.NOTION_PARENT_PAGE_ID }}
        run: |
          python -m src.agent_logic.notion_sync
